spring:
  application:
    name: security-module
  mvc:
    cors:
      allowed-origins: http://localhost:5173
      allowed-headers: '*'
      allowed-methods: GET,POST,PUT,DELETE
  web:
    cors:
      api:
        path-pattern: /api/**
  ldap:
    embedded:
      base-dn: dc=springframework,dc=org
      credential:
        password: admin
        username: uid=admin
      ldif: classpath:users.ldif
      port: 8389
      validation:
        enabled: false
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  secret: 25d9c0e2e11ff6c3cd3769483a0b57664d76b933c428622b026ff52ff8a37fb2
  expiration: 86400000 # 24 saat
logging:
  level:
    root: INFO
  file:
    name: myapp.log
    max-size: 10MB
    max-history: 10
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
springdoc:
  api-docs:
    path: /swagger-ui/security/v3/api-docs
  swagger-ui:
    path: /swagger-ui/security/swagger-ui.html